name: 'Add Secure Code Warrior contextual training to SARIF'
description: 'GitHub Action for adding contextual application security training material to SARIF files based on CWE references'
author: 'SecureCodeWarrior'
branding:
  icon: 'shield'  
  color: 'orange'
inputs:
  inputSarifFile:
    description: 'Relative location of SARIF file to process'
    required: true
    default: './findings.sarif'
  outputSarifFile:
    description: 'Relative destination location for processed SARIF file'
    required: true
    default: './findings.processed.sarif'
  githubToken:
    description: 'Provide `secrets.GITHUB_TOKEN` to use the GitHub access token automatically supplied by GitHub Workflows'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
